name: Build installer for supported OS
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-app:
    name: Build the application
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ macos-latest, ubuntu-latest, windows-latest ]
        os: [ ubuntu-latest, windows-latest ]

    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - id: setup-java
        name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
          cache: 'gradle'

      - id: build-distribution
        name: Build Distribution
        run: ./gradlew jpackage

      - id: create-distribution-folder
        name: Create Distribution Folder
        run: mkdir -p distribution-${{ matrix.os }} && cp -r build/jpackage/* distribution-${{ matrix.os }}

      - id: upload-installer
        name: Upload Installer
        uses: actions/upload-artifact@v3
        with:
          name: PomodoroTime-${{ matrix.os }}
          path: distribution-${{ matrix.os }}

  release-app:
    name: Release the application
    needs: build-app
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ macos-latest, ubuntu-latest, windows-latest ]
        os: [ ubuntu-latest, windows-latest ]

    steps:
      - id: download-installer
        name: Download installer
        uses: actions/download-artifact@v3
        with:
          name: PomodoroTime-${{ matrix.os }}

      - id: create-release
        name: Create GitHub Release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release-${{ github.sha }}
          release_name: release-${{ github.sha }}
          draft: false
          prerelease: false

      - id: release-installer
        name: Release Installer
        uses: actions/upload-release-asset@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: distribution-${{ matrix.os }}
          asset_name: PomodoroTime-${{ matrix.os }}
          asset_content_type: application/zip